<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDfNlzqO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDfNlzqO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDfNlzqO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDfNlzqO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDfNlzqO\App_KernelDevDebugContainer([
    'container.build_hash' => 'DfNlzqO',
    'container.build_id' => 'c87c0242',
    'container.build_time' => 1718874305,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDfNlzqO');
