<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmhn7CN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmhn7CN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmhn7CN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmhn7CN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLmhn7CN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lmhn7CN',
    'container.build_id' => '0ae9f911',
    'container.build_time' => 1719599929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmhn7CN');
